flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform-strings
- ../uniform-error
- ../uniform-algebras
- ../uniform-fileio
- ../uniform-time
# not really needed, but seems to find the old ones 
- ../../fromOthers/path
- ../../fromOthers/path-io
- ../../fromOthers/pretty-show
# - ../../fromOthers/bibtex
extra-deps:
- test-invariant-0.4.5.0
- lens-aeson-1.0.2
resolver:  lts-13.12
