 
resolver: lts-13.12 
packages:
- .
- ../uniform-algebras
- ../uniform-error
- ../uniform-strings
- ../uniform-fileio
- ../../fromOthers/path
- ../../fromOthers/path-io
extra-deps:
- test-invariant-0.4.5.0
