flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform-strings
- ../uniform-error
- ../uniform-algebras
- ../uniform-json
- ../uniform-fileio
- ../../fromOthers/path
- ../../fromOthers/path-io

extra-deps:
- test-invariant-0.4.5.0
resolver: lts-12.26
