flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform-strings
- ../uniform-error
- ../uniform-algebras
- ../uniform-fileio
- ../../fromOthers/bibtex
- ../../fromOthers/path
- ../../fromOthers/path-io
- ../../fromOthers/pretty-show
extra-deps:
- test-invariant-0.4.5.0
resolver: lts-13.12
